### ISSUE TITLE
Code generations takes too long on my machine

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1004]
This is on my Mac, as make render/detailed/detailed.codecgen.go doesn't work if you are building in a container.

```
Toms-MacBook-Pro:scope twilkie$ time make BUILD_IN_CONTAINER=false report/report.codecgen.go render/render.codecgen.go render/detailed/detailed.codecgen.go
env -u GOARCH -u GOOS env GO15VENDOREXPERIMENT=1 go build -tags netgo -o vendor/github.com/ugorji/go/codec/codecgen/codecgen ./vendor/github.com/ugorji/go/codec/codecgen
cd report && env -u GOARCH -u GOOS /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/ugorji/go/codec/codecgen/codecgen -u -o report.codecgen.go controls.go counters.go edge_metadatas.go id.go id_list.go latest_map.go metrics.go networks.go node.go node_set.go report.go sets.go string_set.go topology.go
cd render && env -u GOARCH -u GOOS /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/ugorji/go/codec/codecgen/codecgen -u -o render.codecgen.go filters.go id.go mapping.go memoise.go render.go renderable_node.go selectors.go theinternet.go topologies.go topology_diff.go
cd render/detailed && env -u GOARCH -u GOOS /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/ugorji/go/codec/codecgen/codecgen -u -o detailed.codecgen.go docker_labels.go labels.go metadata.go metrics.go node.go parents.go summary.go

real	0m58.983s
user	2m33.159s
sys	0m14.228s
```

**Comment by 2opremio** [comment]
https://github.com/weaveworks/scope/commit/c741ee74d2ce11f0f7947487b7648ad594007458 makes the situation much better (codecgen was building the world again due to the mismatching tags).

Other ideas:

 * Generate codecs independently for each file. I am not sure this will help since codecgen uses `go run`, which will probably build the whole package each time.
 * Somehow pass `-i` to `go run`. Unfortunately, codecgen will build the world and discard if invoked in a clean build. I even have a branch passing `-i` to go run https://github.com/2opremio/go-1/commit/c99c16dd7787e9a24ca61630968d288bf870b0c6 ... but go run doesn't accept it. To fix this we could modify codecgen to use `go build` + exec a binary instead of using go run.

**Comment by 2opremio** [comment]
Reported the problem upstream: https://github.com/weaveworks/scope/issues/1004
