### ISSUE TITLE
`docker rm -f`ed containers linger

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1072]
seen with scope 0.13...

`docker rm -f <C>`ing a containers linger in the UI for 20s. Not always - @2opremio can reproduce this quite reliably on a single machine, but I only see it when running the app on my desktop and the probe in a VM.

I've also observed this for short-lived containers started with `--rm`.

By contrast `docker kill <C>; docker rm <C>` removes the container from the UI immediately, so does `docker kill <C>` on its own.

**Comment by 2opremio** [comment]
There's a [race](https://github.com/weaveworks/scope/blob/2982166e03b02459e15e08d14e4ab3dbf8f033a9/probe/docker/registry.go#L236-L244) calling `InspectContainer()` when containers are removed `rm`ed. The inspection fails because the cotinainer doesn't exist anymore, and we simply remove the container from the probe state without notifying the UI.
