### ISSUE TITLE
it's not obvious that terminals are extensions of the details panel

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1152]
I only discovered by accident that closing the details panel also closes any associated terminal panel - up until that point I had been dutifully closing the latter and then the former.

Can we make the relationship between the two more obvious?

Perhaps the terminal could look like (and reveal like) a side pull-out from the details panel?

@peterbourgon says such ideas were discussed before. Might be worth revisiting.

**Comment by peterbourgon** [comment]
Namely

```
+----------+ +---+
|          | |   |
|          | |   |
|          | |   |
|          | |   |
+----------+ +---+
```
vs
```
           +---+
+----------|   |
|          |   |
|          |   |
+----------|   |
           +---+

**Comment by rade** [comment]
right. I'd happily give up a few pixels of vertical space.

**Comment by davkal** [comment]
Yes, we stood before those two choices before, and went with the side-by-side for more terminal rows.
I'm curious @rade , what was your intent on closing the details panel?
What where you trying to do next (given that the terminal would have stayed open)?

**Comment by rade** [comment]
My intent was to close both the terminal and details panel, which I had always been doing by closing the terminal first and then details panel. One time I accidentally closed the details panel first, which is how I discovered this useful feature.

**Comment by davkal** [comment]
There are multiple ways to signal the hierarchy:

via covering a smaller element
![screen shot 2016-04-12 at 09 50 01](https://cloud.githubusercontent.com/assets/859729/14453337/7eabb418-0094-11e6-8e8d-27ef9d2a5448.png)

being the base for a smaller element
![screen shot 2016-04-12 at 09 53 15](https://cloud.githubusercontent.com/assets/859729/14453382/be6c0bc0-0094-11e6-9d6d-11044a314583.png)

being the base for a bigger element
![screen shot 2016-04-12 at 09 57 30](https://cloud.githubusercontent.com/assets/859729/14453422/06bda30c-0095-11e6-8a10-3bc3a23004da.png)

being directly connected w/ a subtle shadow
![screen shot 2016-04-12 at 09 59 43](https://cloud.githubusercontent.com/assets/859729/14453483/6ac524e2-0095-11e6-840f-4b93bdfb005a.png)

(original for comparison)
![screen shot 2016-04-12 at 10 01 13](https://cloud.githubusercontent.com/assets/859729/14453508/8fbc5d88-0095-11e6-8a36-90e98ccd0d5d.png)

I find the *base* metaphor works best on me. If I was to close that details panel, I would definitely expect the terminal be closed too. The problem there is that we dont have much margins left for a terminal to expand into, for the expansion cannot be too insignificant, otherwise it will look misaligned, as opposed to deliberately placed (although we could shrink the details panel a tiny bit when the terminal opens).

**Comment by rade** [comment]
For me, none of these work very well. Simply because they all look like possible arrangements in my window manager, where I certainly would not expect that closing one window closes another.

So I think the trick is to make the terminal look less like a "window like any other".

**Comment by peterbourgon** [comment]
Perhaps @rade's request can be accomplished by eliminating separate dropshadows, making the terminal+panel appear as a single entity. Albeit modular, since you can still kill the terminal independent of the panel...

**Comment by davkal** [comment]
No dropshadows make it harder to tell where the window bar begins.
![screen shot 2016-04-12 at 10 59 56](https://cloud.githubusercontent.com/assets/859729/14455046/c68b724c-009d-11e6-9f3f-c60f9f843ab0.png)
I'm guessing a solution for @rade would be to get rid of the window bar. But it hosts 2 buttons and the container name, giving the user additional assurances on which instance this shell is working on.

**Comment by rade** [comment]
perhaps change the "x" to "->"? Or move both control buttons to the left.

**Comment by davkal** [comment]
Maybe a vertical window bar?
```
             +—---+
           +-|    |
+----------|x|    |
|          |>|    |
|          | |    |
+----------| |    |
           +-|    |
             +—---+

```

**Comment by rade** [comment]
> Maybe a vertical window bar?

Kinda awkward for the title.

I think moving the buttons to the left might well be sufficient.

And perhaps animating the opening and closing as a "pull out" and "push in". I know, I know.

**Comment by tomwilkie** [comment]
Perhaps the issue here is that we have things (terminals, details panel) that look like windows but don't behave like them.

They don't behave like them as we decided MDI was a bad thing (something I still agree with), and that we would never be able to do a great job of being a window manager.  They look like windows because our navigation mechanism is a "canvas" with stuff on top, and we need buttons etc to get back to the canvas.

I wonder if revisiting the canvas w/ stuff on top would potentially solve this problem.  What are the other options?

**Comment by davkal** [comment]
> Kinda awkward for the title.

There would be no title in the vertical bar, just buttons.

> I think moving the buttons to the left might well be sufficient. 

Moving buttons + what other change listed here? How does that change your perception of dependence?

> And perhaps animating the opening and closing as a "pull out" and "push in".

That certainly helps. But that still leaves the question about the relationship of the 2 elements when you missed the animation.

**Comment by rade** [comment]
> Moving buttons + what other change listed here?

your last screenshot

> How does that change your perception of dependence?

When the buttons are on the right, they break the continuity between the panel and window.

**Comment by davkal** [comment]
> Perhaps the issue here is that we have things (terminals, details panel) that look like windows but don't behave like them.

Good point. I remember users wanting to drag that terminal toolbar. Maybe less window-y and closer together could work.

> I wonder if revisiting the canvas w/ stuff on top would potentially solve this problem. What are the other options?

I dont think we're there yet. Maps-style overview+detail still works well. But worth keeping in mind.

**Comment by foot** [comment]
1. Joined but w/ colour change
![screen shot 2016-09-27 at 17 22 21](https://cloud.githubusercontent.com/assets/22008/18880092/02febbea-84d7-11e6-9372-ce124063557f.png)

2. Joined w/ colour change + parental border above toolbar.
![screen shot 2016-09-27 at 17 21 23](https://cloud.githubusercontent.com/assets/22008/18880094/03070caa-84d7-11e6-9aed-8ff5cf3ae713.png)

3. Joined w/ colour change + parental border around toolbar
![screen shot 2016-09-27 at 17 21 48](https://cloud.githubusercontent.com/assets/22008/18880093/02fedddc-84d7-11e6-90bf-bc3d95a45f48.png)

**Comment by rade** [comment]
How hard would it be to do a slide in/out animation? I reckon combined with option 2 that might give enough visual cues that the terminal is a "child" of the details panel.

**Comment by foot** [comment]
Pretty straight forward but its a big slide, might be annoying, maybe slide out + immediate close. We can have a go.

**Comment by rade** [comment]
it could slide out/in very rapidly indeed and still provide the desired effect.
