### ISSUE TITLE
Node animation lags behind edge animation

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1242]
(Discussed on a hangout with @davkal)

**Comment by davkal** [comment]
Can reproduce with debug toolbar...

**Comment by davkal** [comment]
This happens when new edges are created that connect to nodes that are moving to a new position. Those edges currently dont animate because they have no prior state.

A possible fix would be passing the source and target nodes from a previous layout run (cant be the current state because those are the final positions) to the edge and injecting those coords as prior waypoints into the edge (via react-motion's `defaultStyle`).

This is not a regression, seen in 0.13, removing milestone.

**Comment by tomwilkie** [comment]
I've seen this when no new edges are coming in; just by clicking the redraw button.
