### ISSUE TITLE
Support for custom shell in scope ui

### ISSUE THREAD

**Issue by kesavkolla** [weaveworks/scope#1251]
When we select a container in weave ui it gives several actions.  One of the action is to launch Shell (Exec /bin/sh).  Is it possible to use custom exec command?  Specially custom shell like (Exec /bin/bash -l).  I've some profile settings that I want to execute during shell init.

**Comment by 2opremio** [comment]
@kesavkolla Thanks for reporting this, the problem is that Scope currently doesn't use any storage where to persist that configuration (https://github.com/weaveworks/scope/issues/1053#issuecomment-190269113)

The upcoming version of Scope (0.14, to be released this week)  will detect the default shell for the user (see https://github.com/weaveworks/scope/pull/1069 ). Would that be enough for you?

**Comment by davkal** [comment]
If the shell detection is not enough, how about a `scope launch` argument for a custom shell?

**Comment by tomwilkie** [comment]
0.14 has just been release.
