### ISSUE TITLE
External host pseudo nodes make hosts view messy

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1311]
This is the host view in the service (3 hosts)  on 0.13.1

http://g.recordit.co/tDmK67mnx5.gif

(it's a video reproducing a bug but please disregard that and just look at the number of nodes)

This is how it looks now:

<img width="1747" alt="screen shot 2016-04-15 at 11 27 46" src="https://cloud.githubusercontent.com/assets/2362916/14559041/fdd0759c-02fd-11e6-9aa7-94359e4452b3.png">

Report: [report.json.gz](https://github.com/weaveworks/scope/files/220769/report.json.gz)

**Comment by tomwilkie** [comment]
I think you may have attached the wrong report - the dates in this one are from 2015-11-23, and a current app fails to ingest it.

**Comment by tomwilkie** [comment]
Here is a more recent report showing the problem: 

[report.json.zip](https://github.com/weaveworks/scope/files/223511/report.json.zip)

**Comment by tomwilkie** [comment]
These are not external host pseudo nodes - they are in fact connections between process etc.  They problem is they do not have pids on them, although they are from procspy (we filter out conntracked connections in this view).

You can also see them in the process view for this report.  You do not see it in the containers view, as we do the funky join on IP address, which also captures this nodes I believe.  Am investigating further.

**Comment by tomwilkie** [comment]
> You do not see it in the containers view, as we do the funky join on IP address, which also captures this nodes I believe. Am investigating further.

Actually we're intentially filtering out non-internet pseudo nodes from the container view: https://github.com/weaveworks/scope/blob/master/render/mapping.go#L229

I don't think we should be, but we do need to know why there are so many pseudo nodes (there should not be that many in the procspied endpoints).

**Comment by tomwilkie** [comment]
So it seems these pseudo nodes are legitimate connections from other process; due to the rate limiting of procspy we don't see the other end of them, so we can't associate them with a process.  This clearly needs fixing, but might take a while)

In the meantime, the suggestion is we filter out all non-internet pseudo nodes from all views - process, container & pod (already done) and hosts.  This should at least make the views useable again.

In the medium term, we need to fix the procspy issue.
