### ISSUE TITLE
Incorrect number of connections shown on internet nodes

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1495]
The +17 is wrong:

![screen shot 2016-05-12 at 16 55 36](https://cloud.githubusercontent.com/assets/444037/15221215/6ef5a6ce-1862-11e6-8ca1-672023aa6793.png)

**Comment by tomwilkie** [comment]
This will be the table ids not being unique again...

**Comment by rade** [comment]
> This will be the table ids not being unique again...

@tomwilkie please elaborate. Is this a f/e or b/e issue?

What I am seeing in e.g. "Weave Cloud (Prod)" is that the 'show more' count is something like "+1126", but expanding the list only adds about 120 items. The other thing that is odd here is that only 2 items are shown by default - looking at the code, the default should be 5.

All that makes me think that it is a f/e issue. @davkal @foot

**Comment by davkal** [comment]
> This will be the table ids not being unique again...

@tomwilkie Correct. This effect can be seen by the first 5 shown (only 2 are rendered because the other 3 are duplicates) and the collapsed ones (there seemed to be 120 unique rows among the 1126 entries). We're using a row's `id` field for that, so a solution would be to make that unique.

**Comment by rade** [comment]
I find it hard to believe that we actually have 1126 connections to AWS services / the internet in prod. 120is a more plausible figure. perhaps the data contains genuine duplicates?

**Comment by rade** [comment]
To reproduce:
```
$ scope launch
1c41ae18a677d54463e23e3adc5e63516b7409688634db79a9d8df5dcc9d635e
Weave Scope is reachable at the following URL(s):
  [...]
$ google-chrome http://localhost:4040
$ docker run --rm --name=foo -ti alpine /bin/sh
/ # IP=$(getent hosts cloud.weave.works | cut -d ' ' -f 1)
/ # echo $IP
52.3.116.14
/ # nc $IP 80 &
/ # 
[1]+  Stopped (tty input)        nc ${IP} 80
/ # nc $IP 80 &
/ # 
[2]+  Stopped (tty input)        nc ${IP} 80
/ # 
```
(the 'Stopped' lines appear after hitting return)

Wait for the 'foo' container and connection to the Internet node to show up in scope and then bring up the details panel on the Internet node. You should see something like
![screenshot_2016-09-01_22-30-09](https://cloud.githubusercontent.com/assets/109109/18185301/e9e95c9c-7094-11e6-8ef3-de729c91739d.png)

Notice that
  - the count for the connections from 'foo' says '1' instead of '2'
  - only 3 rows are shown when the renderer is supposed to render 5 by default
  - expanding the table adds far fewer rows than the shown count
