### ISSUE TITLE
table mode

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1621]
Allow users to list nodes in a tabular view instead of a connected topology.

Related: https://github.com/weaveworks/scope/tree/grid-view https://github.com/weaveworks/scope/issues/1614 https://github.com/weaveworks/scope/issues/1092 https://github.com/weaveworks/scope/issues/1032

**Comment by pidster** [comment]
This 'view' should be a mode, not a new full view (so a given topology can switch to table and back again) - implying the need for an additional view toggle.

**Comment by rade** [comment]
Things to think about

- columns to show - for starters, I suggest the primary and secondary label, plus the items from the 'status' and 'info' sections of the details panel
- dealing with large column entries - some columns can contain a large amount of data, e.g. list of IPs, labels
- sorting - should be possible
- searching - should be possible; like in the topology mode, it should be possible to search for things that aren't shown, e.g. labels
- add/remove/reorder columns - can probably leave that for later
- re-sizing on browser window re-size
- location of details panel - clicking on a row should pop up the details panel - but where? over the table? next to the table?

**Comment by rade** [comment]
problems we are trying to solve here:
- show top n of anything - this is difficult in any of the existing modes

Note we still need the details panel, because there is just too much info per item, especially list info (e.g. list of connections) that can be squeezed into a single row.

More things to think about:
- selecting rows can be made difficult when the items shift around. Imaging trying to hit a 'stop container' control and accidentally hitting the wrong one because the row moved. Suggestion: stop things from moving when hovering over an item. Perhaps, additionally, allow pinning.
