### ISSUE TITLE
explain search syntax (better)

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1762]
From a user...

> It would also be good to have a list of all the search params you can use in the search field, for example I had to figure out I can use namespace:prod

**Comment by foot** [comment]
Search spaces:
 - Basic
  - label, value of `{node.label, node.subLabel}`
  - label, value in `metadata`, `parents`, `tables` (`envvars` and `labels`)
 - Metrics (activated when we see `{<, =, >}` in the expression):
  - label, value in `metrics`

Notes on label matching:
- If labels have spaces in them they are removed before we try and match.
 - `parentpid: 415` will match while `parent pid: 415` will not. (rethink this?)

Breaking down the query:
- If we can parse the query as a regex we do and match against the above `values`
 - `scope|app`
- If query not valid regex we look for the substring anywhere in values:
 - `scope`
- If we can split the expression into _2 parts_ with `:` e.g. `"a:b".split() && parts.length == 2` we match `a` as a regex if valid otherwise string against any of the labels and `b` as a regex if valid otherwise string against all the values.
 - `pid|parentpid:4[12]4`
- If the expressions contains one of `{<, =, >}` split on the operator, treat lhs as a string that must completely match, rhs can have a kb/mb/gb/tb suffix that is partially matched. Only searches in the metrics space:
 - memory > 640 (640 bytes)
 - memory > 640k (640kb)
 - memory > 640kb
