### ISSUE TITLE
Topology filters are not applied to detail panel connections or children

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1864]
Because we don't send topology filters to the details panel.

I argue that this is correct. The topology filters are about *which nodes* should appear, but the data on the details panel is an integral part of the node, and should not be modified, based on topology filters.

@rade argues the opposite.

**Comment by rade** [comment]
Here are a couple of examples of where I think current approach "goes wrong":
![screenshot_2016-09-14_20-15-28](https://cloud.githubusercontent.com/assets/109109/18526335/1a3d0772-7ab8-11e6-8ab5-ed3dbf6ae345.png)
Notice that the services connected to The Internet in the topology are different from what is shown in the list in the details panel. They are included in the expanded list, of course; the issue here is that the list includes the services from all namespaces, not just the "monitoring" namespace I have selected.

![screenshot_2016-09-14_20-27-48](https://cloud.githubusercontent.com/assets/109109/18526758/bee56cdc-7ab9-11e6-8db8-917d2e8f30d8.png)
Notice that the topology tells me that the 'nats' image is used by one container, but the details panel shows two. That's because it shows both stopped and running containers, when the filter is in fact set to 'stopped'.

I reckon most users will be confused by this behaviour.

**Comment by rade** [comment]
AFAICT the filters aren't being passed to the b/e when fetching the data for the detail panels. Contrast the handling of options in [`getTopologies`](https://github.com/weaveworks/scope/blob/v0.17.1/client/app/scripts/utils/web-api-utils.js#L119) with the lack thereof in [`getNodeDetails`](https://github.com/weaveworks/scope/blob/v0.17.1/client/app/scripts/utils/web-api-utils.js#L166). 

@davkal @paulbellamy am I on the right track?

**Comment by paulbellamy** [comment]
Yes, that is the case. That way, if you have the details panel open, and switch topologies, you don't get a blank "node not found" view on the details panel.

**Comment by tomwilkie** [comment]
Another case: if you stop a container and are filtering stopped containers,
you would also get a "node not found".  As a rule we didn't apply topology
filter to the details view.

**Comment by rade** [comment]
> if you have the details panel open, and switch topologies, you don't get a blank "node not found" 

All detail panels close when switching views.

> if you stop a container and are filtering stopped containers, you would also get a "node not found".

Right. IMO that is not a big deal. Ideally we would apply the filters only to the "contents" of the details panel, not the panel itself. I am guessing that is hard in the current code base.

**Comment by paulbellamy** [comment]
I meant "Switch topology filters".

**Comment by paulbellamy** [comment]
>  I am guessing that is hard

Correct.

**Comment by rade** [comment]
So another odd thing that can happen as a result of the current scheme is that the "show me this node int the topology" button brings up a blank canvas, e.g.

![screenshot_2016-09-16_00-55-27](https://cloud.githubusercontent.com/assets/109109/18571201/81ffd0f6-7ba8-11e6-9fe4-8922dd723c94.png)

(I got there by clicking on 'authfe', which is in the selected 'default' namespace, but has connections to services in other namespaces; in this case I clicked on the 'distributor' connection, which is in the 'frankenstein' namespace; this brings up the details panel for it, and then clicking on the "show me in the topology" shows the above)

**Comment by davkal** [comment]
I vote for keeping the current behavior because the locality of the filtering is too far, half-way across the screen, and difficult to keep track of mentally.

For the topology switcher, I can see that this can be confusing. I propose to reset the topology filter (namespace etc) to defaults when clicking that button.

**Comment by rade** [comment]
> I vote for keeping the current behavior because the locality of the filtering is too far, half-way across the screen, and difficult to keep track of mentally.

The same rationale can be applied for arguing the opposite: the details panel opens on the canvas and sits next to / on top of the topology. So having the panel show information that (apparently) disagrees with the topology is confusing.

The situation is made considerably worse by the fact that the information in the details panel does not contain namespaces. So there really is no clue to indicate to the user that they are looking at information across namespace. (This probably deserves a separate issue).

Here's an idea: how about greying out the information in the details panel that doesn't match the current filters?

> I propose to reset the topology filter (namespace etc) to defaults when clicking that button.

The default filters don't show everything. e.g. for containers the defaults only show running application containers, not stopped or system containers. Hence the "blank canvas" problem would still exist.

**Comment by 2opremio** [comment]
> Notice that the services connected to The Internet in the topology are different from what is shown in the list in the details panel

I have also run into this and it's really confusing. However, it doesn't seem we have consensus on what we should do. 

I am with @rade in that the topology filtering should be applied to the details pane.
