### ISSUE TITLE
scope probes should be in kube-system namespace

### ISSUE THREAD

**Issue by lukemarsden** [weaveworks/scope#1891]
otherwise they show up as if they're part of the app.

[weave net daemonset](https://github.com/weaveworks/weave-kube/blob/master/weave-daemonset.yaml) correctly uses kube-system namespace.

**Comment by lukemarsden** [comment]
this touches on @errordeveloper's yaml generator for cloud, so tagging him here

**Comment by rade** [comment]
> this touches on @errordeveloper's yaml generator for cloud

Is there anything else involved? The yaml generator is in the service repo, not scope.

**Comment by 2opremio** [comment]
@errordeveloper Insisted on the probes not being on the kube-system namespace because apparently Openshift doesn't include it.

I am in favor of using the kube-system namespace and updating the resource definitions to mirror the ones we use in Weave Cloud (which don't use service env variables anymore).

**Comment by 2opremio** [comment]
Moved to relevant repository
