### ISSUE TITLE
scope-probe appears to have connection to everything

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1929]
![screenshot_2016-10-18_03-58-47](https://cloud.githubusercontent.com/assets/109109/19462842/5b25cb9a-94e7-11e6-8403-0e18f461fadf.png)

I wonder whether this is somehow a consequence of #1863 and associated DNS tracking PRs.

**Comment by 2opremio** [comment]
@rade Where did this happen? Do you have a report?

**Comment by rade** [comment]
just look at the [kube-system namespace in Weave Cloud Dev in Weave Cloud Dev](http://frontend.dev.weave.works/app/proud-wind-05#!/state/{%22controlPipe%22:null,%22topologyViewMode%22:%22topo%22,%22nodeDetails%22:[],%22pinnedMetricType%22:null,%22pinnedSearches%22:[],%22searchQuery%22:%22%22,%22selectedNodeId%22:null,%22gridSortBy%22:%22process_memory_usage_bytes%22,%22gridSortedDesc%22:true,%22topologyId%22:%22services%22,%22topologyOptions%22:{%22processes%22:{%22unconnected%22:%22hide%22},%22containers%22:{%22system%22:%22application%22,%22stopped%22:%22running%22,%22pseudo%22:%22hide%22},%22pods%22:{%22namespace%22:%22kube-system%22,%22pseudo%22:%22hide%22}}}).

**Comment by 2opremio** [comment]
The probes are doing a good job tagging the containers as being in the host network and tagging the pause container as not making connections

<img width="2305" alt="screen shot 2016-10-21 at 13 00 55" src="https://cloud.githubusercontent.com/assets/2362916/19596847/fecbc9ec-9790-11e6-82d5-335713d89662.png">

<img width="466" alt="screen shot 2016-10-21 at 13 12 04" src="https://cloud.githubusercontent.com/assets/2362916/19596856/088a6934-9791-11e6-8bac-c2c04e51ce77.png">


<img width="617" alt="screen shot 2016-10-21 at 13 11 33" src="https://cloud.githubusercontent.com/assets/2362916/19596858/148bd308-9791-11e6-89a8-76dd37e0ea39.png">


<img width="580" alt="screen shot 2016-10-21 at 13 15 10" src="https://cloud.githubusercontent.com/assets/2362916/19596860/1923cb46-9791-11e6-84a2-61647d51d8ff.png">


so, I am suspecting a regression on  https://github.com/weaveworks/scope/pull/1653 (or perhaps https://github.com/weaveworks/scope/pull/1597 )

**Comment by 2opremio** [comment]
I found out what's happening. [We are taking Pod IPs as unique when matching short-lived connections against them](https://github.com/weaveworks/scope/blob/73e2effb9fc527ea75249736489f135668aa211d/render/pod.go#L142). This is perfectly fine for pods using their own networking namespace like the following:

<img width="2203" alt="screen shot 2016-10-21 at 16 09 58" src="https://cloud.githubusercontent.com/assets/2362916/19601336/375afa2c-97a9-11e6-96ae-d77b29ba5bf2.png">



However, pods in the host networking namespace inherit their IP from the host. For instance:

<img width="2199" alt="screen shot 2016-10-21 at 16 09 31" src="https://cloud.githubusercontent.com/assets/2362916/19601290/fe142356-97a8-11e6-8bdb-425cd36654b1.png">

This causes Scope to attribute all the host connections to a single POD running in the host networking namespace.

No regression here, this has been broken since we started tracking POD connections.

The way to fix this is to check whether the pod runs in the host networking namespace to discard the short-lived connections from/to its IP. Unfortunately, this will also discard legitimate short-lived connections coming from the POD.

**Comment by rade** [comment]
Hmm. We should be able to disambiguate these connections, and "assign" them to the right pod, by taking into account the port - the IP+port combo of the source of outbound connections and the destination of inbound connections should be associated with an individual process, which in turn will give us the pod.

**Comment by 2opremio** [comment]
We don't have PIDs for short-lived connections. So we have the exact same problem for Pods as we have for containers.

In other words, we can't currently disambiguate them. ebpf should change this.

**Comment by 2opremio** [comment]
You have a more thorough explanation in https://github.com/weaveworks/scope/issues/1260

**Comment by 2opremio** [comment]
We don't have PIDs for short-lived connections. So we have the exact same
problem for Pods as we have for containers.

**Comment by 2opremio** [comment]
In other words, we can't currently disambiguate them. ebpf should change
this.
