### ISSUE TITLE
Honor DOCKER_HOST in the probes

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1975]
Right now we hardcode the docker endpoint to `unix:///var/run/docker.sock`

**Comment by rade** [comment]
#1626 is related.

**Comment by rndstr** [comment]
@2opremio regarding [your comment](https://github.com/weaveworks/scope/pull/1973#discussion_r86452088):

> However, this won't be the usecase since scope also needs to live in the machine being monitored (it needs /proc and conntrack for instance)

Does it even make sense to honor `$DOCKER_HOST `automatically? Will this lead to confusion if `$DOCKER_HOST` is unexpectedly set and /proc and conntrack are not from the same host? I could think of an explicit `-probe.docker.env=true` to alleviate this in case that's an issue, otherwise we could just go with auto-detection. Wdyt?
