### ISSUE TITLE
kubernetes logs don't use full width

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1977]
![](https://www.dropbox.com/s/wqo3y8jsrp1hsjh/Screenshot%202016-11-04%2006.15.48.png?dl=1)

**Comment by errordeveloper** [comment]
If someone could give me pointers, I can attempt to fix it.

**Comment by 2opremio** [comment]
And ... This is the use case I was referring to in #1966 , should be easy to fix.

**Comment by 2opremio** [comment]
This will slip the next release though

**Comment by 2opremio** [comment]
> And ... This is the use case I was referring to in #1966 , should be easy to fix.

And I am wrong, now that I look at the code, https://github.com/weaveworks/scope/blob/master/probe/kubernetes/controls.go#L41-L43 doesn't use a TTY. It is probably a UI problem since it also happens when attaching containers and I recall they used to fill the full screen.

<img width="2111" alt="screen shot 2016-11-04 at 08 57 53" src="https://cloud.githubusercontent.com/assets/2362916/19998427/06d74224-a26d-11e6-94ef-6d2e5c1ddada.png">

@jpellizzari / @foot  Mind taking a look? When the pipe doesn't return `tty: raw` ([example](https://github.com/weaveworks/scope/blob/master/probe/docker/controls.go#L160)) the pipe output should be able fill the whole terminal.

**Comment by 2opremio** [comment]
A regression in #1966 ?
