### ISSUE TITLE
CPU usage display

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/scope#1989]
This is more a question than an issue.
When I look in Scope at a container I see e.g. CPU 9%.
When I connect to the same container (via Scope) and do top, I see different usage numbers, e.g. for CPU 18%.

What is the relationship between these numbers, and why do they differ?

**Comment by 2opremio** [comment]
Good question, I would guess it probably has to do with how top measures CPU consumption (e.g. interval sizes) vs how docker does it and the delay sending and displaying metrics from the probes. Maybe the external vs internal view of the container due to cgroups also has an influence (CPU consumption in the host vs cpu consumption with respect to the allocated CPU for the container).

I will investigate, Is the CPU of your container limited in any way? Could you please the output of  `docker inspect container` ? Also can you run `top` and `docker stats container` simultaneously and tell us if there's a difference?

**Comment by rade** [comment]
> Also can you run `top` and `docker stats container` simultaneously and tell us if there's a difference?

I suspect there will be. I have seen this before myself. cgroups resource reporting is ...complicated.

**Comment by bergtwvd** [comment]
Attached the inspect file and a screenshot of top plus docker stats. There is continuously a difference, sometimes small, sometimes larger.

[docker-inspect.txt](https://github.com/weaveworks/scope/files/578064/docker-inspect.txt)

![capture](https://cloud.githubusercontent.com/assets/10650187/20098391/d52d7f96-a5b3-11e6-86af-909d5fc701f9.JPG)

**Comment by 2opremio** [comment]
Your `docker inspect` listing doesn't reveal any CPU quotas so it can't be that.

As you probably have figured out by now, we are simply displaying the CPU percentage obtained by `docker stats` so the difference lies there. 

However, I am now curious myself. Googling for it doesn't reveal the cause and I am not versed enough on cgroups to provide an answer on my own but I will try to dig up an answer.

**Comment by katopz** [comment]
Maybe this related? https://github.com/docker/docker/issues/13626

**Comment by 2opremio** [comment]
> Maybe this related? docker/docker#13626

Yep, most probably

**Comment by rade** [comment]
I actually changed this in #1830, normalising to 100% max, since otherwise one cannot make sense of the metric w/o knowing the number of cores.
