### ISSUE TITLE
sub-label clipped in firefox

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2009]
![screenshot_2016-11-11_13-18-21](https://cloud.githubusercontent.com/assets/109109/20216271/8a63ef9e-a811-11e6-9636-7eb0741d8c74.png)

it's ok on Chrome:

![screenshot_2016-11-11_13-23-37](https://cloud.githubusercontent.com/assets/109109/20216379/1e95b6ac-a812-11e6-8c8d-31b4bd816ea2.png)

**Comment by rade** [comment]
@jpellizzari what's up with this? Are you working on it?

**Comment by jpellizzari** [comment]
This got pushed to the back-burner in favor of other things. I still plan on getting to it on one of our "fix niggling UI issues" days.

**Comment by rade** [comment]
Hmm. I'd rather not leave issues assigned for long w/o any work taking place, unless the assignee really, really doesn't want anybody else to tackle the issue.

**Comment by rndstr** [comment]
I took a stab at this and could not observe this issue for the label in the screenshot. What I *did* see was very long labels that broke out of the label container (due to missing word-separators for line breaking or too many lines) and were clipped by Firefox.

A reaffirming overflow seems to stop FF from clipping these

    .node-labels-container {
        overflow: visible;
    }

but only for the x direction, there is still clipping at the bottom (if it turns into 4 lines).

Whenever text overflows and we manage to make it visible, these things happen intermittently:

- The text part that is outside of the container gets stuck (in relation to the window viewport) once we start moving the graph view. There is no way to get it to invalidate it just stays there even when moving other SVG items over it. 
- it is rendered with a delay; while the in-container label text is rendered instantly, the overflown part shows up half a second later. Specifically visible when a node is selected.

These things might only happen if other nodes/labels are close-by to interfere with rendering or on the right-hand side of the `zoom-content` SVG group.

In Chrome, this all works as intended.

**Comment by rade** [comment]
I cannot see the clipping anymore either. And i don't care about the label container break-out. -> closing.
