### ISSUE TITLE
Scope does not create special nodes within the same VPC

### ISSUE THREAD

**Issue by jasonrichardsmith** [weaveworks/scope#2163]
When utilizing RDS in the same VPC as the the ECS cluster in AWS, scope was not generating special nodes.

When on the same VPC, RDS does not display.  When on a different VPC RDS will display like below.

![db-is-there](https://cloud.githubusercontent.com/assets/1245554/22374126/20db0960-e4a5-11e6-9551-13e5eb5d3d40.png)

**Comment by 2opremio** [comment]
Report to reproduce the issue: 
[report.json.gz](https://github.com/weaveworks/scope/files/735452/report.json.gz)

**Comment by 2opremio** [comment]
I am pretty sure that the problem comes from the connection being local (that's why I suggested using a different VPC)

AFAICR, we only split out out services from connections to the Internet (which, by definition cannot target the local network).

I doubt there's an easy fix for this, but let's see.
