### ISSUE TITLE
Hide Uncontained filter in DNS view not hiding uncontained

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2170]
Select DNS view, and filter by application containers and then filter out uncontained.  You can see that the uncontained are still appearing. 

<img width="1205" alt="screen shot 2017-01-31 at 8 29 09 am" src="https://cloud.githubusercontent.com/assets/13420383/22468774/4468e4d2-e78f-11e6-8fb0-7cd2cac825cb.png">

**Comment by 2opremio** [comment]
Related to https://github.com/weaveworks/scope/issues/2120 ?

**Comment by abuehrle** [comment]
I wasn't private browsing, but I'll try that!  

The hide unmanaged containers filter button doesn't seem to work at all. when you are in the Containers --> DNS view. It does work when you're filtered outside of that.

**Comment by rade** [comment]
just reproduced this on Weave Cloud. @2opremio are you sure this is a UI issue? Is the theory here that the UI is failing to pass the correct filter options to the b/e?

**Comment by 2opremio** [comment]
Yes, that's the theory, but I may be wrong.

**Comment by fbarl** [comment]
@fons I spent some time looking into this (running Scope locally) and here are my observations:

* The UI seems to always pass the correct filter options to the backend
* `IsNotPseudo` method gets called if and only if the *Hide Uncontained* option is selected, which is good
* Output of `IsNotPseudo` doesn't result in correct filtering, e.g.:
  * making it always `return false` still shows the internet nodes (but only them)
  * making it `return n.Topology != Pseudo` doesn't filter out anything, which is weird since the logging inside that method shows that `n.Topology == Pseudo` when `n` is the uncontained node

So my guess would be that the bug occurs when the filters are applied or somewhere deeper. I also tried disabling `renderCache`, but with no results. I'll continue looking into it, but it's taking me some time to really understand what's happening where in the code :)
