### ISSUE TITLE
weavecloud-agent w/o token attempts to talk to local app

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2299]
```
$ docker run --privileged -d --name=weavecloud-agent --net=host --pid=host -v /var/run/docker.sock:/var/run/docker.sock weaveworks/cloud-agent
a6e15b98221ceb697d619933091d215d0af7ca84dc3f336261b49e83c967433d
$ docker logs weavecloud-agent 
time="2017-03-04T11:11:07Z" level=info msg="publishing to: 127.0.0.1:4040" 
<probe> INFO: 2017/03/04 11:11:07.526733 command line args: --logtostderr=true --mode=probe --probe-only=true --probe.docker=true
...
<probe> ERRO: 2017/03/04 11:11:08.528537 Error fetching app details: Get http://127.0.0.1:4040/api: dial tcp 127.0.0.1:4040: getsockopt: connection refused
<repeats every 10 seconds>
```
That only happens when launching the weavecloud-agent without a service token, which is not documented. Still, it's surprising behaviour.

**Comment by 2opremio** [comment]
This is just a side-effect of the agent simply being the result of
repackaging the scope probe. The default target of the probe is
127.0.0.1:4040


We could add an extra mode, "agent" which doesn't set a default target. I
think it still makes sense to let the agent target non-cloud apps if
desired though.

On Mar 4, 2017 12:17, "Matthias Radestock" <notifications@github.com> wrote:

$ docker run --privileged -d --name=weavecloud-agent --net=host
--pid=host -v /var/run/docker.sock:/var/run/docker.sock
weaveworks/cloud-agent
a6e15b98221ceb697d619933091d215d0af7ca84dc3f336261b49e83c967433d
$ docker logs weavecloud-agent
time="2017-03-04T11:11:07Z" level=info msg="publishing to: 127.0.0.1:4040"
<probe> INFO: 2017/03/04 11:11:07.526733 command line args:
--logtostderr=true --mode=probe --probe-only=true --probe.docker=true
...
<probe> ERRO: 2017/03/04 11:11:08.528537 Error fetching app details:
Get http://127.0.0.1:4040/api: dial tcp 127.0.0.1:4040: getsockopt:
connection refused
<repeats every 10 seconds>

That only happens when launching the weavecloud-agent without a service
token, which is not documented. Still, it's surprising behaviour.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/weaveworks/scope/issues/2299>, or mute the thread

**Comment by rade** [comment]
No, it's because of incorrect flag parsing. I've submitted a PR to fix that.

**Comment by 2opremio** [comment]
Uhm, I hadn't looked at the code. Thanks.
