### ISSUE TITLE
Weave Net shows up twice in GUI in ECS

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2458]
An option to view Weave Net shows up twice in the GUI, under Services and under Hosts. 

<img width="1110" alt="screen shot 2017-04-17 at 8 21 11 am" src="https://cloud.githubusercontent.com/assets/13420383/25090112/1485b1a2-2347-11e7-8b53-ee9936d5ec05.png">

**Comment by fbarl** [comment]
A similar thing used to happen to me before (I think `BY IMAGE` Container sub-topology was also appearing under processes), but only when running Scope UI locally and I assumed it had to do with hot reloading... Two questions:

1. Does everything look good when you refresh the page?
2. What happens when you click on both Weave Nets:
  a. Do they show the same topology?
  b. Does it ever happen that the other `WEAVE NET` label is highlighted, and not the one you clicked on?

Also, a bit more info on how you got to that state might be helpful to reproduce the bug. :)

Feels a lot like a UI bug, but wouldn't put the tag before investigating more...

**Comment by abuehrle** [comment]
@fbarl apologies for the vague description.  

I think this occurred when I was running the AWS Cloudformation template for AWS. But let me check that and I will update the issue.

**Comment by 2opremio** [comment]
@abuehrle Is it reproducible?

**Comment by abuehrle** [comment]
No seeing this with our cloudformation template.   This occurred when we were setting up the demo for DockerCon, and we were setting up a preview version of DockerSwarm in Cloud. I will close this one for now and if I see it again will log a new issue.
