### ISSUE TITLE
Permissions error in weave-scope-app running in OpenShift

### ISSUE THREAD

**Issue by andrewlove** [weaveworks/scope#2485]
Deployed weavescope into OpenShift Origin v1.3.1 using documented commands:
```
oc login -u system:admin
oc new-project weavescope
oc project weavescope
oc adm policy add-scc-to-user privileged system:serviceaccount:weavescope:weave-scope
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:weavescope:weave-scope
oc create -f https://cloud.weave.works/k8s/scope.yaml
```
The weave-scope-app container does not deploy successfully.

Looking at the logs I see:
```
mkdir: can't create directory '/var/run/weave': Permission denied  
touch: /etc/service/probe/down: Permission denied  
/home/weave/entrypoint.sh: line 19: /var/run/weave/scope-app.args: No such file or directory  
/home/weave/entrypoint.sh: line 21: /var/run/weave/scope-probe.args: No such file or directory  
runsv probe: fatal: unable to open supervise/lock: file does not exist  
runsv app: fatal: unable to open supervise/lock: file does not exist  
runsv app: fatal: unable to open supervise/lock: file does not exist  
runsv probe: fatal: unable to open supervise/lock: file does not exist  
runsv probe: fatal: unable to open supervise/lock: file does not exist  
...
```

Checking the running processes:
```
/var/run $ ps -ef  
PID   USER     TIME   COMMAND  
    1 10000900   0:00 /home/weave/runsvinit  
   11 10000900   0:00 /sbin/runsvdir /etc/service  
   41 10000900   0:00 /bin/sh -i -c TERM=xterm /bin/sh  
   46 10000900   0:00 /bin/sh  
  195 10000900   0:00 [runsv]  
  196 10000900   0:00 [runsv]  
  197 10000900   0:00 ps -ef  
```

Checking the file permissions:
```
/var $ ls -l  
total 0  
drwxr-xr-x    4 root     root            27 Mar  3 11:20 cache  
dr-xr-xr-x    2 root     root             6 Mar  3 11:20 empty  
drwxr-xr-x    7 root     root            66 Mar 17 21:37 lib  
drwxr-xr-x    2 root     root             6 Mar  3 11:20 local  
drwxr-xr-x    3 root     root            19 Mar  3 11:20 lock  
drwxr-xr-x    2 root     root             6 Mar  3 11:20 log  
drwxr-xr-x    2 root     root             6 Mar  3 11:20 opt  
drwxr-xr-x    3 root     root            20 Apr 27 09:26 run  
drwxr-xr-x    3 root     root            17 Mar  3 11:20 spool  
drwxrwxrwt    2 root     root             6 Mar  3 11:20 tmp  
```

I can't see how user `10000900` can run the `entrypoint.sh` commands `mkdir -p /var/run/weave` etc. The user does not have permissions to create stuff in `/var/run`.

**Comment by alban** [comment]
Yes, Scope must run as root. I am not sure why it is not the case here. [The last time](https://docs.google.com/presentation/d/13_ZEU-T1Gpa_LZAfK-zGYJPoi1cVjqY1btw7KZ6aDkQ/edit#slide=id.g20a866a9e7_0_16) I tried Scope on OpenShift , I used slightly different `oc` commands:

```
oc new-project weavescope
oc project weavescope
oc adm policy add-scc-to-user privileged  system:serviceaccount:weavescope:default
oadm policy add-cluster-role-to-user cluster-admin system:serviceaccount:weavescope:default
```

(using "default" instead of "weave-scope")

Does it make a difference for you?

**Comment by andrewlove** [comment]
The `scope.yaml` specifies a service account called `weave-scope`.
If I run the `oc adm` commands using the `default` user rather than `weave-scope` nothing deploys at all; agents, app.
If I run the `oc adm` commands using the user `weave-scope` the agents deploy as does the app. But the app has permissions errors.

**Comment by alban** [comment]
You're right.

Looking at [this documentation](https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/pod_security_context.html), I wonder what "openshift.io/sa.scc.uid-range" annotation and "uidRangeMin" do you have:
```
oc get project weave-scope -o yaml
```

**Comment by andrewlove** [comment]
```apiVersion: v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: system:admin
    openshift.io/sa.scc.mcs: s0:c10,c0
    openshift.io/sa.scc.supplemental-groups: 1000090000/10000
    openshift.io/sa.scc.uid-range: 1000090000/10000
  creationTimestamp: 2017-04-26T16:07:36Z
  name: weavescope
  resourceVersion: "3220452"
  selfLink: /oapi/v1/projects/weavescope
  uid: 76d16f12-2a9a-11e7-9de3-fa163e750d4f
spec:
  finalizers:
  - openshift.io/origin
  - kubernetes
status:
  phase: Active```

**Comment by andrewlove** [comment]
I have managed to work around the problem by issuing the command:
`oadm policy add-scc-to-group anyuid system:authenticated`

This relaxes the security in the cluster so that images are not forced to run as a pre-allocated UID, without granting everyone access to the privileged SCC.

**Comment by mindfulmonk** [comment]
If anyone has a fuller guide on how the managed to get scope on openshift working please share, I'm also getting

```
runsv probe: fatal: unable to open supervise/lock: file does not exist  
```

**Comment by derekmwright** [comment]
I am also seeing this:
```
mkdir: can't create directory '/var/run/weave': Permission denied
touch: /etc/service/probe/down: Permission denied
/home/weave/entrypoint.sh: line 19: /var/run/weave/scope-app.args: No such file or directory
/home/weave/entrypoint.sh: line 21: /var/run/weave/scope-probe.args: No such file or directory
runsv app: fatal: unable to open supervise/lock: file does not exist
```
It appears scope's container was designed for straight docker/k8 and doesn't take OpenShift's selinux permissions into account. I'm not keen on relaxing my clusters permissions just to run this app.

**Comment by errordeveloper** [comment]
We have the following documented (`site/install.md`), but it's commented out for the moment, as it doesn't appear to work in every kind of OpenShift deployment. It certainly works with a kind of cluster configuration you get by running `oc cluster up`.

Please let me know if that works for you.

## <a name="ose"></a>Installing Scope on OpenShift

To install Weave Scope on OpenShift, you first need to login as `system:admin` user with the following command:

    oc login -u system:admin

Next, create a dedicated project for Weave Scope then apply policy permissions that allow Weave Scope to access Kubernetes API:

    oc new-project weave-scope
    oc adm policy add-scc-to-user privileged system:serviceaccount:weave-scope:default
    oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:weave-scope:default

The installation method for Scope on OpenShift is very similar to the one described above for Kubernetes, but instead of `kubectl apply -n kube-system ...` you need to use
`oc apply ...` and install it into the namespace of the `weave-scope` project you have just created, and not the `kube-system` namesapce, i.e.:

If you are to use Weave Cloud run this command:

    oc apply -f 'https://cloud.weave.works/k8s/v1.5/scope.yaml?service-token=<token>'

And if you are to deploy Scope in standalone mode run:

    oc apply -f 'https://cloud.weave.works/k8s/v1.5/scope.yaml'

To access standalone Scope app from the browser, please refer to Kubernetes instructions above.

I am not sure if OpenShift has moved on to Kubernetes 1.6 yet, if that's what you have, please replace `v1.5` with `v1.6` in the URLs.

**Comment by errordeveloper** [comment]
If you are getting error where `mkdir /var/run/weave` fails, running `oadm policy add-scc-to-group anyuid system:authenticated` should resolve it.
