### ISSUE TITLE
conntrack process executed twice

### ISSUE THREAD

**Issue by alban** [weaveworks/scope#2494]
On current master, when running scope without eBPF enabled, I notice two conntrack processes executed with the same parameters:
```
conntrack --buffer-size 212992 -E -o id -p tcp --any-nat
```
Both conntrack processes are long-running processes.

I added debug messages in Scope and I see that `newConntrackFlowWalker` / `conntrackWalker` is executed twice via:
1. probe/endpoint/reporter.go:NewReporter
2. probe/endpoint/connection_tracker.go:newProcfsConnectionTracker

/cc @2opremio @bboreham
other conntrack issues: #2488 ("Faster conntrack parser"), #2118 ("probe: conntrack: fix output parsing")

**Comment by 2opremio** [comment]
We have always created two long running `conntrack` processes.
1. [To obtain NAT information on connections](https://github.com/weaveworks/scope/blob/d60874aca8dee7d4d0c1a1c28f3394e60a5c553b/probe/endpoint/reporter.go#L78) 
2. [To obtain short-lived connections](https://github.com/weaveworks/scope/blob/d60874aca8dee7d4d0c1a1c28f3394e60a5c553b/probe/endpoint/connection_tracker.go#L40) when ebpf isn't enabled.

The command invocations used to be different (`--any-nat` was only provided for (1)) before #2135. Specifically, the `--any-nat` argument was added [here](https://github.com/weaveworks/scope/pull/2135/files#diff-3a1250bca0ad2155e60599f6f0434450R39) as opposed to [how conntrack was originally invoked](https://github.com/weaveworks/scope/pull/2135/files#diff-ceae397120e9afab29105935920a8518L68).

This is a problem. It means that, when eBPF is not enabled, which is the default, we are only showing short-lived connections that are NATed.

This has been happening since 1.3.0 (March 27) and it has prevented Scope from showing short-lived connections between containers living in the same host (which are not NATed).

I am frankly really surprised that nobody has reported this before. Even worse, we didn't have a test for this :(

**Comment by 2opremio** [comment]
As predicted, I can easily reproduce by running these two containers in the same host:

1. docker run --name nginx nginx
2. docker run --name curl tutum/curl bash -c "while true; do curl $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx); sleep 2; done"

Before https://github.com/weaveworks/scope/pull/2527
<img width="1659" alt="screen shot 2017-05-17 at 01 06 36" src="https://cloud.githubusercontent.com/assets/2362916/26132138/795c4f8c-3a9e-11e7-8c75-38c7d0aedb78.png">


After https://github.com/weaveworks/scope/pull/2527

<img width="1659" alt="screen shot 2017-05-17 at 01 08 30" src="https://cloud.githubusercontent.com/assets/2362916/26132142/7d8e07ee-3a9e-11e7-8157-c2b709db4bd4.png">
