### ISSUE TITLE
Force re-layout not working

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2596]
Version: weaveworks/scope:release-1.5-1667984
Docker for Mac
Sockshop
Standalone Scope

Please see: 

http://recordit.co/cZshm6AwXh

**Comment by fbarl** [comment]
@abuehrle What was your expected behaviour? Take a look at my comment here: https://github.com/weaveworks/scope/issues/2564#issuecomment-307779912

I think people have very different ideas what the refresh button should be doing, see the issue https://github.com/weaveworks/scope/issues/2377 and my "fix" https://github.com/weaveworks/scope/pull/2407. :)

**Comment by abuehrle** [comment]
I expected the containers to centre themselves within that view so that you can see all of the containers including the ones that have fallen out of the main view.  When you click the force layout, it appears as if nothing happens.  So the zoom correction was removed? What should I be looking for when I force re-layout?

**Comment by fbarl** [comment]
Yeah, most people seemed very opinionated about this :)

The idea with the refresh button is that it would force relayouting on the graph, meaning the nodes would rearrange if they were not positioned "optimaly", while the zoom state is currently left unchanged by design.

**Comment by abuehrle** [comment]
Ok... I will leave that one.
