### ISSUE TITLE
Scope needs updating for Weave Net 2.0

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#2634]
This code: https://github.com/weaveworks/scope/blob/master/probe/overlay/weave.go  
It's attempting to talk to a weaveproxy container, which no longer exists.

**Comment by rade** [comment]
This is a problem already since in a CNI context the proxy won't be running. Nor will the plugin. Cue lots of log noise that terrifies users - see #2628.

**Comment by rade** [comment]
Would it be reasonable to simply *remove* the plugin and proxy stuff from that code?

**Comment by rade** [comment]
Actually, I guess we should obtain the info from the Weave Net 2.0 status json, since it's included there now. I don't think we should bother keeping the existing code for old Weave Net versions, especially since, as observed above, it can generate log noise there too. We should however make sure that the new status retrieval code can cope with an old version json.
