### ISSUE TITLE
Scope uses more memory than expected.

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#266]
~50MB.  Might be worth looking into.

**Comment by peterbourgon** [comment]
Why is that more than expected?

**Comment by tomwilkie** [comment]
I was expecting something around 10mb.

**Comment by peterbourgon** [comment]
Why would you expect 10MB? Even a do-nothing daemon is ~5MB. (Honest questions, I promise.)

**Comment by tomwilkie** [comment]
No real reasoning, I guess we should set an expectation. Looking at it
today we seem to have gone up to 150MB so I wonder if there's a leak.

Weaver and DNS both use about 10MB

**Comment by tomwilkie** [comment]
Even worse:
```
Created
24 Jun 15 10:14 UTC
Command
/home/weave/entrypoint.sh --dns 172.17.42.1 --searchpath weave.local
Memory Usage (MB):
413.07
```

**Comment by bboreham** [comment]
I did some diagnosis on this, although I did not have the opportunity to observe a process at ~50MB.

I started scope, built from master.  I only have a few containers running on my machine, and they are not connected to any other machines.  Linux sees the size as 18MB:

````
$ grep -i VM /proc/25014/status
VmPeak:	   18676 kB
VmSize:	   18676 kB
````

After half an hour, the size has grown very slightly:

````
$ grep -i VM /proc/25014/status
VmPeak:	   18932 kB
VmSize:	   18932 kB
````

Since scope is linked with pprof, we can view its internal stats at http://127.0.0.1:4040/debug/pprof/heap?debug=1 (scroll to the bottom):

Soon after startup:
````
# runtime.MemStats
# Alloc = 4,178,904
# TotalAlloc = 301,409,080
...
# HeapInuse = 5,193,728
# HeapReleased = 0
...
# NextGC = 5,059,840
````

(I inserted the commas to make the numbers easier to read)

`Alloc` is how much memory is allocated now; `TotalAlloc` is how much memory has been allocated since the program started; the difference between these numbers is the amount of garbage collected.

When `Alloc` hits the level of `NextGC`, the next garbage-collect will run.

After half an hour we see:

````
# Alloc = 4,984,624
# TotalAlloc = 2,563,262,288
...
# HeapInuse = 6,356,992
# HeapReleased = 802,816
...
# NextGC = 5,633,072
````

So a lot of garbage has been collected and released, but the overall amount of memory in use has grown only slightly.  It has peaked and gone down again, marked by the `HeapReleased` figure.

There is a good overview of profiling techniques [on the Intel blog](https://software.intel.com/en-us/blogs/2014/05/10/debugging-performance-issues-in-go-programs)

We can use the command-line pprof tool to analyze where all this garbage is coming from:

````
$ go tool pprof -alloc_space http://127.0.0.1:4040/debug/pprof/heap
Fetching profile from http://127.0.0.1:4040/debug/pprof/heap
Saved profile in /home/bryan/pprof/pprof.127.0.0.1:4040.alloc_objects.alloc_space.001.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
2287.70MB of 2873.39MB total (79.62%)
Dropped 116 nodes (cum <= 14.37MB)
Showing top 5 nodes out of 52 (cum >= 133.60MB)
      flat  flat%   sum%        cum   cum%
 1606.28MB 55.90% 55.90%  1606.28MB 55.90%  github.com/weaveworks/scope/report.IDList.Add
  205.51MB  7.15% 63.05%   509.55MB 17.73%  encoding/gob.decodeIntoValue
  197.58MB  6.88% 69.93%   197.58MB  6.88%  reflect.Value.SetMapIndex
  159.73MB  5.56% 75.49%   371.27MB 12.92%  github.com/weaveworks/scope/render.LeafMap.Render
  118.59MB  4.13% 79.62%   133.60MB  4.65%  github.com/weaveworks/scope/render.RenderableNodes.Merge
````

So we can easily see that IDList.Add is the top culprit.  I created #309 to reduce this to clear some of the noise and make it easier to drill down further.

**Comment by 2opremio** [comment]
I have been investigating the memory consumption of master. I am not (yet) very familiar with Go's GC/profiling, so I may be getting wrong conclusions, please correct me if I am wrong.

After launching Scope in a clean VM (no running or stopped containers) with `scope launch --probe.http.listen :4041` I get.

* 9MB for the probe:

   ```
$ go tool pprof http://127.0.0.1:4041/debug/pprof/heap
Fetching profile from http://127.0.0.1:4041/debug/pprof/heap
Saved profile in /home/vagrant/pprof/pprof.127.0.0.1:4041.inuse_objects.inuse_space.003.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
5398.62kB of 8983.83kB total (60.09%)
Dropped 336 nodes (cum <= 44.92kB)
Showing top 5 nodes out of 67 (cum >= 512.56kB)
      flat  flat%   sum%        cum   cum%
 1700.18kB 18.92% 18.92%  1700.18kB 18.92%  github.com/weaveworks/scope/vendor/github.com/coocood/freecache.NewCache
 1184.27kB 13.18% 32.11%  1184.27kB 13.18%  github.com/weaveworks/scope/vendor/github.com/weaveworks/weave/common.SignalHandlerLoop
 1065.09kB 11.86% 43.96%  1065.09kB 11.86%  github.com/weaveworks/scope/vendor/github.com/prometheus/client_golang/prometheus.newDefaultRegistry
  936.52kB 10.42% 54.39%   936.52kB 10.42%  bytes.makeSlice
  512.56kB  5.71% 60.09%   512.56kB  5.71%  encoding/pem.Decode
```

* 8 MB for the app:

   ```
$ go tool pprof http://127.0.0.1:4040/debug/pprof/heap
Fetching profile from http://127.0.0.1:4040/debug/pprof/heap
Saved profile in /home/vagrant/pprof/pprof.127.0.0.1:4040.inuse_objects.inuse_space.008.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
4814.94kB of 7375.23kB total (65.29%)
Dropped 123 nodes (cum <= 36.88kB)
Showing top 5 nodes out of 57 (cum >= 512.28kB)
      flat  flat%   sum%        cum   cum%
    1541kB 20.89% 20.89%     1541kB 20.89%  github.com/weaveworks/scope/vendor/github.com/coocood/freecache.NewCache
 1184.27kB 16.06% 36.95%  1184.27kB 16.06%  github.com/weaveworks/scope/vendor/github.com/weaveworks/weave/common.SignalHandlerLoop
 1024.34kB 13.89% 50.84%  1024.34kB 13.89%  reflect.mapassign
  553.04kB  7.50% 58.34%   553.04kB  7.50%  github.com/weaveworks/scope/vendor/github.com/prometheus/client_golang/prometheus.newDefaultRegistry
  512.28kB  6.95% 65.29%   512.28kB  6.95%  github.com/weaveworks/scope/vendor/k8s.io/kubernetes/pkg/api/v1.init
```

After launching our local Scope service k8s development cluster (which launches around 30 containers):

* 16MB for the probe

  ```
$ go tool pprof http://127.0.0.1:4041/debug/pprof/heap
Fetching profile from http://127.0.0.1:4041/debug/pprof/heap
Saved profile in /home/vagrant/pprof/pprof.127.0.0.1:4041.inuse_objects.inuse_space.005.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
10.74MB of 16.24MB total (66.13%)
Dropped 366 nodes (cum <= 0.08MB)
Showing top 5 nodes out of 95 (cum >= 1.04MB)
      flat  flat%   sum%        cum   cum%
    5.38MB 33.14% 33.14%     5.38MB 33.14%  bytes.makeSlice
    1.66MB 10.22% 43.36%     1.66MB 10.22%  github.com/weaveworks/scope/vendor/github.com/coocood/freecache.NewCache
    1.50MB  9.24% 52.60%     1.50MB  9.24%  github.com/weaveworks/scope/report.EdgeMetadatas.Copy
    1.16MB  7.12% 59.72%     1.16MB  7.12%  github.com/weaveworks/scope/vendor/github.com/weaveworks/weave/common.SignalHandlerLoop
    1.04MB  6.40% 66.13%     1.04MB  6.40%  github.com/weaveworks/scope/vendor/github.com/prometheus/client_golang/prometheus.newDefaultRegistry
```


* 10 MB for the app
  ```
$ go tool pprof http://127.0.0.1:4040/debug/pprof/heap
Fetching profile from http://127.0.0.1:4040/debug/pprof/heap
Saved profile in /home/vagrant/pprof/pprof.127.0.0.1:4040.inuse_objects.inuse_space.012.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
7.82MB of 11.86MB total (65.93%)
Dropped 231 nodes (cum <= 0.06MB)
Showing top 5 nodes out of 75 (cum >= 1.16MB)
      flat  flat%   sum%        cum   cum%
    2.50MB 21.09% 21.09%     2.50MB 21.09%  reflect.mapassign
    1.50MB 12.69% 33.78%     1.50MB 12.69%  github.com/weaveworks/scope/vendor/github.com/coocood/freecache.NewCache
    1.50MB 12.65% 46.43%     1.50MB 12.65%  encoding/gob.decString
    1.16MB  9.75% 56.18%     1.16MB  9.75%  bytes.makeSlice
    1.16MB  9.75% 65.93%     1.16MB  9.75%  github.com/weaveworks/scope/vendor/github.com/weaveworks/weave/common.SignalHandlerLoop
```

Then I spawned another VM with with the same kubernetes cluster (another ~30 containers), spawned a probe and connected it to the Scope App in the first VM. The apps's memory consumption only increases to approximately 20MB (this value varies, to a maximum of ~25MB).

```
$ go tool pprof http://127.0.0.1:4040/debug/pprof/heap
Fetching profile from http://127.0.0.1:4040/debug/pprof/heap
Saved profile in /home/vagrant/pprof/pprof.127.0.0.1:4040.inuse_objects.inuse_space.023.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top5
12.67MB of 21.03MB total (60.23%)
Dropped 268 nodes (cum <= 0.11MB)
Showing top 5 nodes out of 110 (cum >= 1.16MB)
      flat  flat%   sum%        cum   cum%
    6.50MB 30.92% 30.92%     6.50MB 30.92%  reflect.mapassign
       2MB  9.51% 40.43%        2MB  9.51%  encoding/gob.decString
    1.50MB  7.16% 47.59%     1.50MB  7.16%  github.com/weaveworks/scope/vendor/github.com/coocood/freecache.NewCache
    1.50MB  7.14% 54.73%     1.50MB  7.14%  github.com/weaveworks/scope/report.Metadata.Copy
    1.16MB  5.50% 60.23%     1.16MB  5.50%  bytes.makeSlice
```

I haven't yet checked whether the Scope App/Probe has memory leaks and admittedly two probes is not a very stressful test but it seems reasonable so far.

@tom What setup were you running when you got the 50MB and the 150MB memory consumption (of the App, I assume)

@bboreham As a side note, checking the VM consumption of a Go program doesn't seem meaningful anymore (maybe due to changes in Go 1.5?).

Both the app and the probe consume 300MB of virtual memory:

```
$ grep 'VmPeak\|VmSize'  /proc/$(pgrep -f scope-app)/status
VmPeak:   297696 kB
VmSize:   297696 kB
```

But checking `/proc/$(pgrep -f scope-app)/status` shows that there are large regions (the heap/stack of goroutines?) which effectively account to to virtual memory but which are not mapped to physical memory (yet).

```
[...]
Size:              65404 kB
Rss:                   0 kB
Pss:                   0 kB
Size:                132 kB
Rss:                   4 kB
Pss:                   4 kB
Size:              65404 kB
Rss:                   0 kB
Pss:                   0 kB
Size:               7424 kB
Rss:                7116 kB
Pss:                7116 kB
Size:                  4 kB
Rss:                   0 kB
Pss:                   0 kB
Size:               8192 kB
Rss:                   8 kB
Pss:                   8 kB
Size:                  4 kB
Rss:                   0 kB
Pss:                   0 kB
Size:               8192 kB
Rss:                   8 kB
Pss:                   8 kB
Size:                  4 kB
Rss:                   0 kB
Pss:                   0 kB
Size:               8448 kB
[...]
```

Since my machine doesn't have any Swap, the Pss (Which is very close to the Rss since the apps are statically compiled) should actually account for the actual memory being consumed. We can see the totals with smem:

```
$ sudo smem -k -P '^scope-*'                                                                                                                                                                       
  PID User     Command                         Swap      USS      PSS      RSS 
11822 root     scope-probe probe -docker=t        0    63.8M    71.5M    79.2M 
11823 root     scope-app app                      0    74.0M    81.7M    89.4M
```

Which in fact is not too far away from the consumption pprof reports + the size of the executable (35MB).

**Comment by tomwilkie** [comment]
What does it mean for memory to be attributed to common.SignalHandlerLoop?
I think there is room for improvement in EdgeMetadatas.Copy with ps.Map
techniques.  And I'd love to understand what the reflect.mapassign means
(probably gob/json decoding).

I don't recall what was using 150MB of RAM, but I think it'll probably be
the example app in experimental.  And I think it was the kinda thing where
it was left running for a few days.

**Comment by 2opremio** [comment]
> What does it mean for memory to be attributed to common.SignalHandlerLoop?

The signal handler [allocates a 1MB buffer](https://github.com/weaveworks/weave/blob/9ad1ccf19f191a0af2bb9e2c42dd4907f781ebcf/common/signals.go#L18). While I don't think we should be optimizing buffer allocations for dumping stacktraces (a feature not used in normal situations) I don't think it's a big deal.

> I think there is room for improvement in EdgeMetadatas.Copy with ps.Map
techniques.  And I'd love to understand what the reflect.mapassign means
(probably gob/json decoding).

I will look into this, but I first would like to replicate the high memory usage you mentioned by leaving Scope running for a few days. I don't think that the relatively-small numbers I show above by themselves justify spending too much time into memory optimizations.

BTW, my VM is now freezing every time I launch scope due to #769 so I am going to look into that one first.

**Comment by 2opremio** [comment]
OK, I have replicated the same setup as in my measurements above, retrieving the `Alloc` of the app and probes every 5 minutes.

I will let it run for a couple of days and come back with memory consumption graphs.

**Comment by 2opremio** [comment]
After connecting two probes monitoring ~30 containers each to a Scope App, I obtained this memory consumption timeline. The interpolated line seems to suggest there is a small memory leak but I will wait a bit to confirm:

![scopeappmemoryconsumption](https://cloud.githubusercontent.com/assets/2362916/12614461/0b1e1f72-c4f8-11e5-9eac-9380d67e0252.png)

Here is the result for the probes:

![scopeprobe1memoryconsumption](https://cloud.githubusercontent.com/assets/2362916/12614594/d4424fea-c4f8-11e5-8af8-908e8956fa55.png)



![scopeprobe2memoryconsumption](https://cloud.githubusercontent.com/assets/2362916/12614622/03424638-c4f9-11e5-92a2-e8e76f18ee33.png)






For the record, this is how I obtained the memory consumption information for the App and plotted it with octave. It was done in a similar way for the probes.


```bash
while true; do 
  curl -s 'http://localhost:4041/debug/pprof/heap?debug=1' | sed -n -e 's%^# Alloc = \(.*\)$%\1%p' > app_alloc.txt 
  sleep 300
done
```

```octave
mem = load('app_alloc.txt')';
x = 5/60 * (0:length(mem)-1); 
y = mem/2^20; 
p = polyfit(x,y,1); 
yi = p(2) .+ p(1) .* x ; 

hold on; 
plot(x,y); 
plot(x,yi, 'r'); 
xlabel('Hours'); 
ylabel('MB');  
title('Scope App memory consumption'); 
legend('measured', 'interpolated');
```

**Comment by tomwilkie** [comment]
@2opremio can we close this?  We're working on a more targeted problem in #881.  

Weird this test didn't hit #881.

**Comment by 2opremio** [comment]
I left 077c136 running for a few days with the same test, but calling 'debug/pprof/heap?debug=1&gc=1' to force GCs to dimnish the Allocation variance (thanks for the tipe @bboreham ).

Here are the graphs:

![scopeappmemoryconsumtion](https://cloud.githubusercontent.com/assets/2362916/12720265/cb53dc44-c8f1-11e5-81e2-80ec628cedb4.png)

![scopeprobe1memoryconsumption](https://cloud.githubusercontent.com/assets/2362916/12720268/cf9c88fa-c8f1-11e5-8cdd-b2c1e76d6511.png)

![scopeprobe2memoryconsumption](https://cloud.githubusercontent.com/assets/2362916/12720275/d3b7d412-c8f1-11e5-87e8-d17c8e4789ce.png)


The app doesn't seem to be leaking (or at the very least it's not worrisome). The probes have increasing allocations but I am not sure there are leaks:

* App: http://filebin.ca/2VTc70BGbvTs/pprof.192.168.99.100_4040.inuse_objects.inuse_space.001.pb.gz
![app](https://cloud.githubusercontent.com/assets/2362916/12720632/a74e89dc-c8f3-11e5-8ec5-d0d4b18f7dff.png)

* Probe 1: http://filebin.ca/2VTcK7CFJ3A9/pprof.192.168.99.100_4041.inuse_objects.inuse_space.001.pb.gz

![probe1](https://cloud.githubusercontent.com/assets/2362916/12720702/e2ab8214-c8f3-11e5-8242-60f4d2585b27.png)


* Probe 2: http://filebin.ca/2VTcVfQOULe5/pprof.192.168.99.101_4041.inuse_objects.inuse_space.001.pb.gz

![probe2](https://cloud.githubusercontent.com/assets/2362916/12720736/0aa02c02-c8f4-11e5-8422-75fb73bc3c50.png)


However I don't see anything obvious. 1MB for the inspected containers seems a bit too much, but maybe it's due to stopped containers (I would to check the list of containers to which I don't have access right now).

```
$ go tool pprof scope  pprof.192.168.99.100_4041.inuse_objects.inuse_space.001.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) list updateContainerState
Total: 13.32MB
ROUTINE ======================== github.com/weaveworks/scope/probe/docker.(*registry).updateContainerState in /go/src/github.com/weaveworks/scope/probe/docker/registry.go
         0        1MB (flat, cum)  7.51% of Total
         .          .    235:
         .          .    236:func (r *registry) updateContainerState(containerID string) {
         .          .    237:   r.Lock()
         .          .    238:   defer r.Unlock()
         .          .    239:
         .        1MB    240:   dockerContainer, err := r.client.InspectContainer(containerID)
         .          .    241:   if err != nil {
         .          .    242:           // Don't spam the logs if the container was short lived
         .          .    243:           if _, ok := err.(*docker_client.NoSuchContainer); !ok {
         .          .    244:                   log.Printf("Error processing event for container %s: %v", containerID, err)
         .          .    245:                   return
         .          .    246:           }
         .          .    247:
         .          .    248:           // Container doesn't exist anymore, so lets stop and remove it
         .          .    249:           container, ok := r.containers[containerID]
         .          .    250:           if !ok {
         .          .    251:                   return
         .          .    252:           }
         .          .    253:
         .          .    254:           delete(r.containers, containerID)
         .          .    255:           delete(r.containersByPID, container.PID())
         .          .    256:           container.StopGatheringStats()
         .          .    257:           return
         .          .    258:   }
         .          .    259:
         .          .    260:   // Container exists, ensure we have it
         .          .    261:   c, ok := r.containers[containerID]
         .          .    262:   if !ok {
         .          .    263:           c = NewContainerStub(dockerContainer)
         .          .    264:           r.containers[containerID] = c
         .          .    265:   } else {
         .          .    266:           // potentially remove existing pid mapping.
         .          .    267:           delete(r.containersByPID, c.PID())
         .          .    268:           c.UpdateState(dockerContainer)
         .          .    269:   }
         .          .    270:
         .          .    271:   // Update PID index
         .          .    272:   if c.PID() > 1 {
         .          .    273:           r.containersByPID[c.PID()] = c
         .          .    274:   }
         .          .    275:
         .          .    276:   // Trigger anyone watching for updates
         .          .    277:   for _, f := range r.watchers {
         .          .    278:           f(c)
         .          .    279:   }
         .          .    280:
         .          .    281:   // And finally, ensure we gather stats for it
         .          .    282:   if dockerContainer.State.Running {
         .          .    283:           if err := c.StartGatheringStats(); err != nil {
(pprof) 
```

@tomwilkie Please have a look, and if you don't see anything obvious let's close this

**Comment by 2opremio** [comment]
> Weird this test didn't hit #881.

The machines are not running Weave Net, they are Kubernetes clusters.

**Comment by tomwilkie** [comment]
This looks fine to me.
