### ISSUE TITLE
new version notification not showing

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2716]
A long time ago - in #1366 - we introduced an indicator in the app, alerting users to the availability of a new version.

Alas it's not working (anymore).

The api call returns the required info...
```
$ curl -s http://localhost:4040/api | jq '.'
{
  "capabilities": {
    "report_persistence": false
  },
  "hostname": "xps",
  "id": "4bcc89dcaf3d8115",
  "newVersion": {
    "downloadUrl": "https://github.com/weaveworks/scope/releases/download/v1.5.1/scope",
    "version": "1.5.1"
  },
  "plugins": [],
  "version": "1.5.0"
}
```
but this is not shown in the UI.

**Comment by rade** [comment]
bonus points for figuring out when this got broken.

**Comment by rndstr** [comment]
@rade I took a quick look over where this might have stopped working but I cannot see how this _ever_ worked? The received update info `newVersion` from the API has _never_ been passed to the react/redux store (in https://github.com/weaveworks/scope/blob/a6d3542c896c409675a708afd888cff19c4df917/client/app/scripts/actions/app-actions.js#L648-L655). Maybe I'm missing something but I also checked out that merge commit of #1366 but it didn't show up as in the posted screenshot.

**Comment by rade** [comment]
Hmm. the screenshot in #1366 immediately follows @davkal's commit of the UI piece, so I would have thought that the latter was produced by the former. Perhaps there's some extra commit missing.

**Comment by davkal** [comment]
The migration from Flux to Redux (96aae9bc9989ba117df1bc7c91c72d1705764cff) broke this in two ways:

1. The action on receiving the newVersion item does not set the new version in the store.

2. The getting of the new version from the redux store cannot work :

https://github.com/weaveworks/scope/commit/96aae9bc9989ba117df1bc7c91c72d1705764cff#diff-63537513399135a955b9e5b988a617b5R44
(`newVersion` is merged into `state` and hence becomes an immutable.js object, with `.get('prop')` accessors instead of `.prop`.

**Comment by rndstr** [comment]
@davkal I thought this as well at first (Flux to Redux seemed to be the culprit) but then I saw that with Flux, [receiveApiDetails()](https://github.com/weaveworks/scope/commit/96aae9bc9989ba117df1bc7c91c72d1705764cff#diff-364a557e54b37e9201c43b1a9f3f93baL167) was called which [did not forward `newVersion`](https://github.com/weaveworks/scope/commit/96aae9bc9989ba117df1bc7c91c72d1705764cff#diff-1e72320ac03e757fcb9a9eaf2f773abcL316) to the store.

Even though the store dispatcher would've [set the `newVersion`]( https://github.com/weaveworks/scope/commit/96aae9bc9989ba117df1bc7c91c72d1705764cff#diff-e92114ae7f6f9172ed3a0e016e392351L693) but I don't see how it could be in the `payload`.

Anyway, I presume I'm missing something somewhere since you (and Tom) both posted screenshots which showed it working.

**Comment by davkal** [comment]
Just tried the actual PR commit when the feature was introduced. It did not work (and can't, by looking at the action creator). The only explanation for why the feature PR has a working screenshot is that it was mocked up in the footer component.
