### ISSUE TITLE
On groupings which traverse hosts (process-by-name or container-by-image), you can't tell which hosts the details come from

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#296]
In the details panel you see multiple "origin process" tables, and you don't know which is from which host.

I suggest we change the name of the table to be the same as the major (minor) of the node, ie they should be something like "Process Apache (341 - host1)" or "Conatiner Weave (host1)" or something

**Comment by peterbourgon** [comment]
Agreed.

**Comment by 2opremio** [comment]
This implies obtaining the hostname when rendering the `Process` and `Container` topologies in the details pane. I see three possible ways to obtain the hostname:

1. Obtain the hostname from the `Host` `Topology` but this is messy since not all reports are guaranteed to contain it.
2. Add the hostname to every `Process` and `Container` `Topology`s.
3. Add the hostname to the `Report` .

I will go for (2) but let me know if you think I should do otherwise.

**Comment by tomwilkie** [comment]
A report is merge from multiple hosts, so we can't do 3.

We have the same problem when rendering labels for containers and processes (see https://github.com/weaveworks/scope/blob/master/render/mapping.go#L111).  We currently just use the host id, which is in every node metadata (see https://github.com/weaveworks/scope/blob/master/probe/host/tagger.go).

So basically, (2).

**Comment by 2opremio** [comment]
Thanks @tomwilkie , will go for 2.

**Comment by peterbourgon** [comment]
I'm sorry I missed this. For the record, every report is guaranteed to contain the host topology, as every report necessarily originates from a host.
