### ISSUE TITLE
"Connections" and "Connection details" seem redundant in the details panel

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#322]
We could merge them, potentially making the details bit expand on demand or something.

**Comment by 2opremio** [comment]
Before I get down to code it, and as suggested by @davkal here's the sketch of my proposal. Sorry for my shitty photoshop skills:
<img width="1500" alt="proposal" src="https://cloud.githubusercontent.com/assets/2362916/9384990/bb1afd8a-474b-11e5-8efe-bbfca16adcba.png">

The idea is to have expandable tables, which you expand by clicking on the `+` button (and condense again by pressing the `-` button). We can do this in two steps in order to avoid involving @davkal  right away since he has more important stuff on his plate.

1. Merge the *Connection Details* table  into the *Connections* table an marking the *Connection Details* rows as *expandable* (I will add a new table attribute for this). @davkal  can simply start by ignoring this attribute (which I would guess that's what the code does right now). 
2. As soon as @davkal has the time he can add the table expansion to the UI by checking the *expandable* attribute of the rows.

@tomwilkie @davkal Thoughts?

**Comment by tomwilkie** [comment]
I like this proposal.  When you do the merge, can you move the connections table to the bottom (until its expandable).

For the expandability icon, an upside-down pyramid might be more fitting with material design.  I'll leave that up to david.

**Comment by 2opremio** [comment]
Yep, I didn't know about the guide until now, it does cover [list Expand/collapse](https://www.google.com/design/spec/components/lists-controls.html#lists-controls-types-of-list-controls) and it unsurprisingly looks better than my sketch :)

<img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQscFNfNmMwVENBWDA/components_listcontrols_expand1.png" width="300"> <img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsMVI2c1hiTWdXRUE/components_listcontrols_expand2.png" width="300">


Ok, I will get down to code it then and I will move it to the bottom while at it.
