### ISSUE TITLE
I want to send data to my demo,what should i do 

### ISSUE THREAD

**Issue by heiy** [weaveworks/scope#3374]
I want to send data to my demo
not send http://localhost:4040
what should i do

**Comment by aleks-mariusz** [comment]
if you're asking about making scope be exposed to outside the cluster (so it can be reached without using kubectl proxy / kubectl port-forward), you can use something like setting up [an ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/) on the weave-scope-app service.  

but should probably consider what kind of security restrictions may also be necessary, as scope has no built-in authentication/authorization capabilities of its own.   And since exposing scope essentially gives anyone using scope full access to your cluster, you should at the simplest level at least use something like ingress with basic auth (requiring a username and password) (unless perhaps, your kubernetes cluster (minikube?) is a very unimportant/lab/isolated cluster, but remember even then, giving someone scope access essentially means they can run things from the network kubernetes is on as well).

one last thing, this isn't the right place to ask questions/seek help with something like this.  github issues are for reporting actual _issues_ with the code/software/app that's hosted in the repo.  that you aren't sure how to do something isn't really an issue with the code :-) but more a question/request for help.  the right place to ask that is on (the #scope chat channel)[https://weave-community.slack.com/messages/C985DLV6F/] hosted on slack.  you'll probably get quicker help and more people replying there (depending on time of day).

**Comment by dholbach** [comment]
Thanks @aleks-mariusz for the thoughtful reply. I'm closing this issue for now.

Maybe it'd be worth adding a FAQ doc to Scope with your reply? :-)
