### ISSUE TITLE
Are we doing anything to prevent the same report being send to the same app twice?

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#463]

**Comment by tomwilkie** [comment]
Peter has some idea here.  The prototype I hacked up shouldn't be merged.

This probably isn't a release blocker.

**Comment by peterbourgon** [comment]
The actual issue is that the same app instance may be reachable via several IPs, which all get picked up by the probe via weaveDNS. (Perhaps other methods, too.) Probes broadcast their reports to all upstreams, which is a fundamental error in design, but was something we decided to do in the short-term to help in ease of use.

The proper fix is something along the lines of:

1. Have some kind of peer daemon, ideally as a separate process in the weavescope container
1. The peer connects to all other weavescope peers via existing methods & performs master election
1. The peer injects configuration to its app and probe

The quick and dirty fix is probably:

1. Change the app to reply to each POST with a unique ID
1. With each new app target, the probe should POST an empty report and receive the unique ID
1. Probe builds a map of unique ID to list of app targets (implies sorting)
1. With each publish, probe will send to the first app for a given unique ID
1. Probe will regularly (~60s?) re-resolve its known app targets to deal with changes

**Comment by tomwilkie** [comment]
Quick & dirty approach sounds fine.  Only suggestion would be to not overload the report-posting endpoint, and instead stick the app id in /api (which also has the version, and should be useful in the future).  As the resolver calls MultiPublisher.Add() repeatedly, you could fetch /api there and not need the extra timeout for the probe to re-check ids.

**Comment by peterbourgon** [comment]
Good ideas. Updated.

**Comment by tomwilkie** [comment]
@peterbourgon And this?

**Comment by peterbourgon** [comment]
Yep.
