### ISSUE TITLE
Coloring, tagging, naming, describing

### ISSUE THREAD

**Issue by faddat** [weaveworks/scope#556]
I'd like to be able to put text on connection lines in between nodes (hosts, containers, or apps, doesn't matter) in Scope.  That way, 9/10ths of the explaining can be done visually.  This said I wouldn't want this to be a fully-auto option because:

 * The automation might not do it well enough
 * the automation is missing that "human contextualization" 
 * I often have info the machine doesn't

As for the nodes themselves, I'd like to be able to assign colors myself, and tell Scope the meaning of the color so that it can build a key for quick reference.  

Here's another good-to-have:

 * Hardware spec is an area where the host has just as much info as I do.  Visually exposing that information can help in countless ways.

**Comment by peterbourgon** [comment]
Thanks for the ideas! The colors themselves are incidental, but the idea of a key is interesting. We've also had some internal discussion about visualizing hardware specs, e.g. resource availability & utilization, we'll definitely put more weight to that now.

Regarding user customization, at the moment, the Scope UI is read-only, for a number of reasons, not least because the product is largely stateless. We also resist customization in the way you describe; we want the UI to be almost functional, taking your containers/application/infrastructure as input, and yielding a useful, deterministic UX as output.

Thanks for the ideas!
