### ISSUE TITLE
weave container has no IP address

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/scope#595]
I get the following error message when launching scope with weave already running:
weave container has no IP address; is Docker networking enabled?

If I launch scope before weave, then scope starts up fine.

DOCKER_HOST is not set.

**Comment by tomwilkie** [comment]
Hi bergtwvd; this is because you're running the latest Weave (1.2).  We've go a fix (#560) in the the next release of Scope, which should be out in the next few days.  In the meantime, you use a master build of Scope (grab a scope script from here https://raw.githubusercontent.com/weaveworks/scope/master/scope) that should work.

Thanks

Tom
