### ISSUE TITLE
2 totally fresh azure VMs display "empty scope when connected via weave"

### ISSUE THREAD

**Issue by faddat** [weaveworks/scope#611]
Okay，this one certainly is gist-worthy.  There are no other machines besides these 2 vms in the network.  The gist is the full history from inception for both VMs.  

https://gist.github.com/faddat/8fa6e132daa9a4c41dee

**Comment by tomwilkie** [comment]
Hi Jacob; sorry for the radio silence.  I think the problem is you we're using the combination of weave 1.2 and scope 0.8; some of the changes in 1.2 broke scope, so we just release 0.9 which should fix those issues: http://blog.weave.works/2015/11/02/weave-scope-0-9-released/

Let me know if this helps. Thanks, Tom

**Comment by tomwilkie** [comment]
(See #560 for more details)

**Comment by faddat** [comment]
I think I was already on 0.9, but I'll give it a whirl.

Thanks!

-Jake

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by faddat** [comment]
Scope and weave still don't seem to be behaving consistently-- weave may have one thing, but scope then tells me that it is connected to another.  It's really a puzzle.  I'll post more logs, etc when I'm booted up again.

**Comment by tomwilkie** [comment]
@faddat looking forward to those logs :-)

**Comment by faddat** [comment]
user error
