### ISSUE TITLE
Implement ./scope help

### ISSUE THREAD

**Issue by tommyogp** [weaveworks/scope#768]
Default port of weave scope is 4040. Anyway to do `scope launch` with a different port?

**Comment by tomwilkie** [comment]
Hi Tommy!  It is indeed possible:
```
./scope launch --app.http.address :80 localhost:80
```
The first argument tells the app to listen on port 80, the second argument tells the probe to send reports to the app on port 80.

This could  be make nicer - for instance we should add a `./scope help` command that lists the command line options.

**Comment by pidster** [comment]
+1 for improving help.

**Comment by tommyogp** [comment]
@tomwilkie :+1: for the help command list

**Comment by tomwilkie** [comment]
So the problem with providing better help is that scope's entrypoint.sh does some basic parsing of the arguments before it passing them to the app & probe.  Therefore, we can't just print the output of `scope app -help` etc.

Since the scope and the probe are now one binary which looks at the first argument and then executes either the probe main or the app main, I suggest we move the flag handling into the common main function.  That way, we can pass the same arguments to `./scope app` and `./scope probe`, and use the output of `./scope -help` to close this issue.

Any other suggestions?

**Comment by paulbellamy** [comment]
I had a go at using `github.com/spf13/cobra` for sub-commands, which is nice, except it uses pflags, which runs us into [this issue](https://github.com/kubernetes/kubernetes/issues/21148)
