### ISSUE TITLE
Make probes use https with Scope Service

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#777]
The Scope Service now supports https. Thus, the probes should use https instead of http. AFAIU this can be done simply by reverting https://github.com/weaveworks/scope/commit/d57d4aa53ac18fae7477dc8bb1b3372d8fe087ae

While we are at it, it would be good to avoid implicitly including `scope.weave.works` in the probe's targets when `--service-token` is provided. 

For instance, contrary to what the user expects the command `scope launch --service-token=foo my.own.scope.service.com:80`  will try to send reports to both `my.own.scope.service.com:80` and `scope.weave.works:80`.

**Comment by foot** [comment]
I've found that I don't get anything sent to the 2nd host. (or maybe nothing sent at all, I'm not sure if stuff is going to `scope.weave.works`). E.g. Running locally like this:

` 2632 root       0:00 /home/weave/scope probe -docker=true -token=9s95dcemze1ztbigthubtay9mwxaniws scope.weave.works:80 frontend.dev.weave.works:80`

In the scope service dev UI:
 - No new "(connected)" probe in "Configure your app"
 - Nothing to show in scope topo view.

Changing `docker/entrypoint.sh` as described in weaveworks/service#275 so that frontend.dev.weave.works is the only entry works and I get probes in the dev service UI!

**Comment by 2opremio** [comment]
I don't see how that's related to this ticket. If it happens in master (and
from your comment I believe it does), it deserves a ticket of its own.

Related to #698 and #630
