### ISSUE TITLE
Crossing lines and immovable bobbles

### ISSUE THREAD

**Issue by squaremo** [weaveworks/scope#863]
<img width="644" alt="screen shot 2016-01-27 at 16 40 15" src="https://cloud.githubusercontent.com/assets/62033/12620938/423e3776-c516-11e5-92c2-ea3fb6730de5.png">

My first instinct is: I need to move that bobble so I can see the lines properly. Result: the whole thing moves. Close tab.

**Comment by tomwilkie** [comment]
Yes, unfortunately this can happen as a result of us being really persistent about not moving nodes (due to the dancing bugs).  The UI keeps an in memory cache of where the nodes are, so its should be possible for us to allow users to move a node and remember where it is, at least from a brief period.

We should also add a <img width="32" alt="screen shot 2016-01-27 at 18 46 40" src="https://cloud.githubusercontent.com/assets/444037/12633398/52927d98-c526-11e5-990e-dd0c9a08879d.png"> button to relayout the screen.

**Comment by foot** [comment]
Ah hah, `hungry_hopper` is the offender?
