### ISSUE TITLE
TestAll seems flaky

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#896]
```
--- FAIL: TestAll (0.25s)

	scope_test.go:77: api_topology_test.go:37: Expected status 200, got 404. Path: /api/topology/pods-by-service/container%3A5e4d3c2b1a
```

https://circleci.com/gh/weaveworks/scope/2739?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by tomwilkie** [comment]
https://circleci.com/gh/weaveworks/scope/2742

**Comment by tomwilkie** [comment]
This is pretty easy to reproduce.  I think it has to be something to do with the merging of renderable nodes.

**Comment by paulbellamy** [comment]
Based on a couple failing cases with some logging, I am wondering if it is caused by conflicting cache hits.

Reflect.Value.Pointer docs say, "the returned pointer is an underlying code pointer, but not necessarily enough to identify a single function uniquely." Whether that is causing this bug or not, it's certainly a (serious) bug.
